all: main1 main2 main3

main1: main1.c operations.c
	gcc -std=c99 -O2 main1.c operations.c -o main1
main2: main2.c operations.c
	gcc -std=c99 -O2 main2.c operations.c -o main2
main3: main3.c operations.c
	gcc -std=c99 -O2 main3.c operations.c -o main3
